### ISSUE TITLE
paps.c:283:3: error: ‘pango_parse_enum’ is deprecated [-Werror=deprecated-declarations]

### ISSUE THREAD

**Issue by l29ah** [dov/paps#31]
paps refuses to build with pango-1.42.4:
```
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /var/tmp/portage/app-text/paps-0.7.1/work/paps-0.7.1/config/missing autoheader)
configure.ac:14: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:314: AC_GNU_SOURCE is expanded from...
configure.ac:14: the top level
rm -f stamp-h1
touch config.h.in
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-recursive
make[1]: Entering directory '/var/tmp/portage/app-text/paps-0.7.1/work/paps-0.7.1'
Making all in src
make[2]: Entering directory '/var/tmp/portage/app-text/paps-0.7.1/work/paps-0.7.1/src'
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I..  -DGETTEXT_PACKAGE='"paps"' -DDATADIR='"/usr/share"'  -fno-strict-aliasing -Wnested-externs -Wmissing-prototypes -Wstrict-prototypes -Wdeclaration-after-statement -Wimplicit-function-declaration -Wold-style-definition -Wjump-misses-init -Wall -Wextra -Wundef -Wwrite-strings -Wpointer-arith -Wmissing-declarations -Wredundant-decls -Wno-unused-parameter -Wno-missing-field-initializers -Wformat=2 -Wcast-align -Wformat-nonliteral -Wformat-security -Wsign-compare -Wstrict-aliasing -Wshadow -Winline -Wpacked -Wmissing-format-attribute -Wmissing-noreturn -Winit-self -Wmissing-include-dirs -Wunused-but-set-variable -Warray-bounds -Wreturn-type -Wswitch-enum -Wswitch-default -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Werror -Wno-suggest-attribute=format -Wno-error=unused-parameter -Wno-error=missing-field-initializers -Wno-format-y2k -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/lib64/libffi-3.3_rc2/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -O2 -pipe -march=ivybridge -mtune=native -ftree-vectorize -c -o paps-paps.o `test -f 'paps.c' || echo './'`paps.c
paps.c: In function ‘parse_enum’:
paps.c:283:3: error: ‘pango_parse_enum’ is deprecated [-Werror=deprecated-declarations]
   ret = pango_parse_enum (type,
   ^~~
In file included from /usr/include/pango-1.0/pango/pango.h:46,
                 from paps.c:23:
/usr/include/pango-1.0/pango/pango-utils.h:63:10: note: declared here
 gboolean pango_parse_enum     (GType       type,
          ^~~~~~~~~~~~~~~~
paps.c: At top level:
paps.c:427:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
 get_encoding()
 ^~~~~~~~~~~~
paps.c: In function ‘get_encoding’:
paps.c:427:1: error: old-style function definition [-Werror=old-style-definition]
paps.c: In function ‘main’:
paps.c:540:7: error: unused variable ‘header_sep’ [-Werror=unused-variable]
   int header_sep = 20;
       ^~~~~~~~~~
paps.c:715:6: error: this condition has identical branches [-Werror=duplicated-branches]
   if (do_draw_header)
      ^
paps.c: In function ‘read_file’:
paps.c:821:20: error: unused variable ‘ibleft’ [-Werror=unused-variable]
       gsize iblen, ibleft, oblen;
                    ^~~~~~
paps.c: In function ‘split_text_into_paragraphs’:
paps.c:983:38: error: implicit declaration of function ‘wcwidth’ [-Werror=implicit-function-declaration]
                           gssize w = wcwidth (wtext[i]);
                                      ^~~~~~~
paps.c:983:38: error: nested extern declaration of ‘wcwidth’ [-Werror=nested-externs]
paps.c: At top level:
paps.c:1363:1: error: no previous prototype for ‘get_date’ [-Werror=missing-prototypes]
 get_date(char *date, int maxlen)
 ^~~~~~~~
paps.c: In function ‘draw_page_header_line_to_page’:
paps.c:1422:11: error: unused variable ‘line_pos’ [-Werror=unused-variable]
   gdouble line_pos;
           ^~~~~~~~
paps.c:1420:18: error: unused variable ‘date’ [-Werror=unused-variable]
   gchar *header, date[256];
                  ^~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:445: paps-paps.o] Error 1
make[2]: Leaving directory '/var/tmp/portage/app-text/paps-0.7.1/work/paps-0.7.1/src'
make[1]: *** [Makefile:401: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/app-text/paps-0.7.1/work/paps-0.7.1'
make: *** [Makefile:342: all] Error 2
```

**Comment by dov** [comment]
Fixed in commit:5cf4bd3 . I made a local copy of the deprecated pango function in the paps sources.
